version: '2'

services:
    mysql:
        image: mysql:latest
        platform: linux/amd64
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - 3306:3306
        environment:
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=thangthang
            - MYSQL_USER=thangnv
            - MYSQL_PASSWORD=thangthang
            - MYSQL_DATABASE=facebook_job